### ISSUE TITLE
Supporting Cake 0.25's #module directives

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake-vso#43]
Using Cake 0.25's [`#module` directive](https://cakebuild.net/docs/fundamentals/preprocessor-directives#module-directive) requires invoking Cake twice, the first time with `--bootstrap`.

It appears as though this extension is not doing that. ~~How soon can we expect that?~~ How easy of a change do you think this is—is it something I can help with?

**Comment by gep13** [comment]
@jnm2 I might be having a bad day, but let's be clear on something...

> How soon can we expect that?

This is an Open Source Project, and as such, you can't have any expectations, and if I am being brutally honest, using language such as this doesn't make anyone want to jump onto helping with this.

Now, I am going to go out on a limb, since you are an open source maintainer yourself, that this is just a turn of phrase, and you aren't trying to put any sort of pressure on the Cake Team here, but I do feel that it needs to be said.

Also, as we have also said a number of times, if you are able to help out with a PR, then that is the most sure fire way of getting this type of request shipped.

**Comment by jnm2** [comment]
Oh my goodness, I'm very sorry! You are quite right. 😳 Making someone's day worse is the last thing I want to do, so I'm very glad you took the time to say something. I'll be more sensitive.

**Comment by gep13** [comment]
> Making someone's day worse is the last thing I want to do, so I'm very glad you took the time to say something. I'll be more sensitive.

I am very glad to hear that we are on the same page :+1:

**Comment by jnm2** [comment]
I think I know what contributes to me rushing to catch up with issues and saying something I didn't realize. I'll catch up on sleep and slow down over here. In the meantime your feedback was thoughtful and I hope you feel free to clue me in if I end up off-base again.
