### ISSUE TITLE
Release major version of the extension

### ISSUE THREAD

**Issue by gep13** [cake-build/cake-vso#63]
As discussed on Gitter...

>@devlead said...
It's versioned, but because the way Azure DevOps work we should rev major and not minor. Even if you pin version Azure DevOps will automatically silently upgrade minor versions.

**Comment by richardgavel** [comment]
If you do this, are you thinking of re-releasing what I guess would be the 0.4.1 codebase so that people pinning to 0.x would see the earlier version?

**Comment by gep13** [comment]
@richardgavel the current released version is 0.4.3.  There are a couple of enhancements/changes that were originally slated to go into a 0.5.0 release, but I was thinking about changing those to be in the 1.0.0 release, and to ship when they have been added.

Does that make sense?

**Comment by richardgavel** [comment]
I was asking mainly because I am seeing an issue where when my Cake shells
out to a exe and standard error is getting truncated. This is behaviour
that I've seen with Azure Devops before with their Powershell task (but I
never saw it with the original Cake extension using the legacy Powershell
handler for custom extensions). Probably going to fork this from that last
working version for now.
